import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { doctor } from "../src/doctor.js";

async function fixture(t) { const root = await mkdtemp(path.join(os.tmpdir(), "potassium-doctor-")); t.after(() => rm(root, { recursive: true, force: true })); const scripts = path.join(root, "scripts"); const workspace = path.join(root, "workspace"); const autoexec = path.join(root, "autoexec"); await Promise.all([mkdir(scripts, { recursive: true }), mkdir(workspace, { recursive: true }), mkdir(autoexec, { recursive: true }), mkdir(path.join(root, "potassium-mcp"), { recursive: true }), mkdir(path.join(root, ".omp"), { recursive: true })]); const bootstrap = 'local ENDPOINT = "ws://127.0.0.1:32145"\nlocal ok, token = pcall(readfile, ".potassium-mcp-token")\n'; const autoexecText = "return true\n"; await writeFile(path.join(scripts, "potassium_mcp_bootstrap.lua"), bootstrap); await writeFile(path.join(scripts, "potassium_mcp_autoexec.lua"), autoexecText); await writeFile(path.join(workspace, ".potassium-mcp-bootstrap.lua"), bootstrap); await writeFile(path.join(autoexec, "potassium_mcp_autoexec.lua"), autoexecText); await writeFile(path.join(root, "potassium-mcp", "config.json"), JSON.stringify({ host: "127.0.0.1", port: 32145, tokenFile: "../workspace/.potassium-mcp-token", artifactRoots: [{ name: "artifacts", path: "../workspace/potassium-mcp-artifacts", recursive: true, extensions: [".json"] }] })); await writeFile(path.join(root, ".omp", "mcp.json"), JSON.stringify({ mcpServers: { potassium: { type: "stdio", command: "node", args: [path.join(root, "potassium-mcp", "src", "server.js")], timeout: 30000 } } })); return { root, scripts, workspace, autoexec }; }
const options = (value) => ({ projectRoot: value.root, scriptSourceRoot: value.scripts, workspaceRoot: value.workspace, autoexecRoot: value.autoexec, checkStyLua: false });
test("doctor verifies config, launcher, two-script parity, and only two-script style input", async (t) => { const value = await fixture(t); const result = await doctor(options(value)); assert.equal(result.ok, true); assert.deepEqual(result.checks.map(({ name }) => name), ["canonical-scripts", "stylua", "script-parity", "mcp-config", "mcp-server-target"]); });
test("doctor reports a changed deployed script", async (t) => { const value = await fixture(t); await writeFile(path.join(value.autoexec, "potassium_mcp_autoexec.lua"), "changed\n"); const result = await doctor(options(value)); assert.equal(result.ok, false); assert.equal(result.checks.find(({ name }) => name === "script-parity").ok, false); });
