[CmdletBinding()]
param([string]$WorkspaceRoot = $(if ($env:POTASSIUM_WORKSPACE) { $env:POTASSIUM_WORKSPACE } else { Join-Path $env:LOCALAPPDATA "Potassium\workspace" }))
$ErrorActionPreference = "Stop"
function Write-Utf8NoBom([string]$Path, [string]$Content) { [System.IO.File]::WriteAllText($Path, $Content, (New-Object System.Text.UTF8Encoding($false))) }
function Get-PortableRelativePath([string]$BasePath, [string]$TargetPath) { $base = [System.IO.Path]::GetFullPath($BasePath); if (-not $base.EndsWith([System.IO.Path]::DirectorySeparatorChar)) { $base += [System.IO.Path]::DirectorySeparatorChar }; [System.Uri]::UnescapeDataString((New-Object System.Uri($base)).MakeRelativeUri((New-Object System.Uri([System.IO.Path]::GetFullPath($TargetPath)))).ToString()) }
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path; $mcpRoot = Join-Path $projectRoot "potassium-mcp"; $node = Get-Command node -ErrorAction SilentlyContinue
if (-not $node -or [int]((& $node.Source --version).TrimStart("v").Split(".")[0]) -lt 22) { throw "Node.js 22 or newer is required." }
if (-not (Test-Path -LiteralPath $WorkspaceRoot -PathType Container)) { throw "Potassium workspace was not found. Start Potassium once or pass -WorkspaceRoot." }
$workspaceRoot = (Resolve-Path -LiteralPath $WorkspaceRoot).Path; $tokenPath = Join-Path $workspaceRoot ".potassium-mcp-token"
if (-not (Test-Path -LiteralPath $tokenPath) -or (Get-Content -LiteralPath $tokenPath -Raw).Trim().Length -lt 32) { $bytes = New-Object byte[] 32; $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create(); try { $generator.GetBytes($bytes) } finally { $generator.Dispose() }; Write-Utf8NoBom $tokenPath "$( [Convert]::ToBase64String($bytes) )`n" }
try { $acl = Get-Acl -LiteralPath $tokenPath; $acl.SetAccessRuleProtection($true, $false); foreach ($rule in @($acl.Access)) { [void]$acl.RemoveAccessRule($rule) }; [void]$acl.AddAccessRule([System.Security.AccessControl.FileSystemAccessRule]::new([System.Security.Principal.WindowsIdentity]::GetCurrent().User, "FullControl", "Allow")); Set-Acl -LiteralPath $tokenPath -AclObject $acl } catch { Write-Warning "Could not restrict token ACL: $($_.Exception.Message)" }
$config = Get-Content -LiteralPath (Join-Path $mcpRoot "config.example.json") -Raw | ConvertFrom-Json; $config.tokenFile = Get-PortableRelativePath $mcpRoot $tokenPath; $artifactRoot = Join-Path $workspaceRoot "potassium-mcp-artifacts"; New-Item -ItemType Directory -Force -Path $artifactRoot | Out-Null; $config.artifactRoots[0].path = Get-PortableRelativePath $mcpRoot $artifactRoot; Write-Utf8NoBom (Join-Path $mcpRoot "config.json") ($config | ConvertTo-Json -Depth 8)
$ompRoot = Join-Path $projectRoot ".omp"; New-Item -ItemType Directory -Force -Path $ompRoot | Out-Null; $launcherPath = Join-Path $ompRoot "mcp.json"; $launcher = if (Test-Path $launcherPath) { Get-Content $launcherPath -Raw | ConvertFrom-Json } else { [PSCustomObject]@{ '$schema' = "https://raw.githubusercontent.com/can1357/oh-my-pi/main/packages/coding-agent/src/config/mcp-schema.json"; mcpServers = [PSCustomObject]@{} } }; if (-not $launcher.PSObject.Properties["mcpServers"]) { $launcher | Add-Member NoteProperty mcpServers ([PSCustomObject]@{}) }; $launcher.mcpServers | Add-Member NoteProperty potassium ([PSCustomObject]@{ type = "stdio"; command = "node"; args = @((Join-Path $mcpRoot "src\server.js")); timeout = 30000 }) -Force; Write-Utf8NoBom $launcherPath ($launcher | ConvertTo-Json -Depth 8)
$npm = Get-Command npm -ErrorAction SilentlyContinue; if (-not $npm) { throw "npm is required." }; Push-Location $mcpRoot; try { & $npm.Source ci; if ($LASTEXITCODE -ne 0) { throw "npm ci failed." }; $env:POTASSIUM_WORKSPACE = $workspaceRoot; & $node.Source "src/deploy.js"; if ($LASTEXITCODE -ne 0) { throw "Deployment failed." }; & $node.Source "src/doctor.js"; if ($LASTEXITCODE -ne 0) { throw "Doctor checks failed." } } finally { Pop-Location }
Write-Host "Potassium MCP configured for $workspaceRoot."
