[CmdletBinding(SupportsShouldProcess)]
param([string]$WorkspaceRoot = $(if ($env:POTASSIUM_WORKSPACE) { $env:POTASSIUM_WORKSPACE } else { Join-Path $env:LOCALAPPDATA "Potassium\workspace" }))
$ErrorActionPreference = "Stop"
function Write-Utf8NoBom([string]$Path, [string]$Content) { [System.IO.File]::WriteAllText($Path, $Content, (New-Object System.Text.UTF8Encoding($false))) }
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path; $mcpRoot = Join-Path $projectRoot "potassium-mcp"; $statePath = Join-Path $projectRoot "DEPLOY_STATE.json"; $workspaceRoot = [System.IO.Path]::GetFullPath($WorkspaceRoot); $autoexecRoot = [System.IO.Path]::GetFullPath((Join-Path $workspaceRoot "..\autoexec")); $allowed = @([System.IO.Path]::GetFullPath((Join-Path $workspaceRoot ".potassium-mcp-bootstrap.lua")), [System.IO.Path]::GetFullPath((Join-Path $autoexecRoot "potassium_mcp_autoexec.lua")))
$managed = @()
if (Test-Path -LiteralPath $statePath) {
  try { $state = Get-Content -LiteralPath $statePath -Raw | ConvertFrom-Json } catch { throw "Refusing uninstall: deployment state is unreadable." }
  if ($state.schema -ne 2 -or @($state.files).Count -ne 2) { throw "Refusing uninstall: deployment state does not describe the two managed scripts." }
  foreach ($file in @($state.files)) { $target = [System.IO.Path]::GetFullPath([string]$file.target); if ($allowed -notcontains $target -or -not $file.byteParity -or -not $file.targetSha256) { throw "Refusing uninstall: deployment state names an unmanaged artifact." }; $managed += $target }
} else { Write-Warning "DEPLOY_STATE.json is absent; deployed scripts are preserved because ownership cannot be proven." }
$serverMarker = [Regex]::Escape((Join-Path $mcpRoot "src\server.js")); Get-CimInstance Win32_Process -Filter "Name = 'node.exe'" -ErrorAction SilentlyContinue | Where-Object { $_.CommandLine -match $serverMarker } | ForEach-Object { if ($PSCmdlet.ShouldProcess("node process $($_.ProcessId)", "Stop project MCP server")) { Stop-Process -Id $_.ProcessId -Force } }
foreach ($target in $managed) { if (Test-Path -LiteralPath $target -PathType Leaf -and $PSCmdlet.ShouldProcess($target, "Remove proven project-managed script")) { Remove-Item -LiteralPath $target -Force } }
$launcherPath = Join-Path $projectRoot ".omp\mcp.json"; if (Test-Path -LiteralPath $launcherPath -PathType Leaf) { try { $launcher = Get-Content $launcherPath -Raw | ConvertFrom-Json } catch { throw "Refusing uninstall: MCP launcher is unreadable." }; if ($launcher.PSObject.Properties["mcpServers"] -and $launcher.mcpServers.PSObject.Properties["potassium"]) { if ($PSCmdlet.ShouldProcess($launcherPath, "Remove potassium MCP launcher entry")) { $launcher.mcpServers.PSObject.Properties.Remove("potassium"); if (@($launcher.mcpServers.PSObject.Properties).Count -eq 0 -and @($launcher.PSObject.Properties | Where-Object { $_.Name -notin @('$schema', 'mcpServers') }).Count -eq 0) { Remove-Item $launcherPath -Force } else { Write-Utf8NoBom $launcherPath ($launcher | ConvertTo-Json -Depth 8) } } } }
foreach ($local in @((Join-Path $mcpRoot "config.json"), $statePath)) { if (Test-Path -LiteralPath $local -PathType Leaf -and $PSCmdlet.ShouldProcess($local, "Remove project-managed configuration")) { Remove-Item -LiteralPath $local -Force } }
Write-Host "Removed proven Potassium MCP scripts, configuration, and launcher entry; tokens, artifacts, and unrelated files were preserved."
